@startuml

package Controller{
    class BaseController {

    }

    abstract class MainController{

        }

    class AdminController {

    }

    class ModeratorController {

    }

    class UserController {

    }

    BaseController <--> MainController
    MainController <|-- AdminController
    MainController <|-- ModeratorController
    MainController <|-- UserController

}

package Data{
    package Handler{

    }

    package Mapper{

    }
}

package Model {

}

package Util{

}

package View{
    interface UIInterface{

    }

    class UI {

    }

    UIInterface <.. UI

}

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml